/**
 * Temsili musteri yorumlari (anasayfada her sayfa yenilemede 4 random gosterim).
 * Bu yorumlar ornek amaclidir; ReviewsSection altinda bunu acikca belirtir.
 */

export type Review = {
  name: string;
  role?: string;
  rating: 4 | 5;
  daysAgo: number;
  text: string;
};

export const reviews: Review[] = [
  { name: 'Ahmet Yılmaz', role: 'Galeri Sahibi', rating: 5, daysAgo: 12, text: 'Otomotiv galerimiz için sıfırdan site kurdular. Araç stoğumuz artık çok daha şık görünüyor, telefon trafiği belirgin arttı.' },
  { name: 'Ayşe Kaya', role: 'Emlak Danışmanı', rating: 5, daysAgo: 28, text: 'Emlak portföyümü yöneten panel mükemmel çalışıyor. İlan ekleme ve takip artık dakikalar sürüyor.' },
  { name: 'Mehmet Demir', role: 'Restoran İşletmecisi', rating: 5, daysAgo: 5, text: 'Restoranımıza özel online rezervasyon sistemi geliştirdiler. Masa doluluğumuz hafta içi günlerde de yükseldi.' },
  { name: 'Zeynep Çelik', role: 'Güzellik Salonu Sahibi', rating: 5, daysAgo: 60, text: 'Salonum için kurdukları randevu sistemi gerçekten hayat kurtardı. Müşteriler online randevu alabiliyor, hata oranımız sıfıra indi.' },
  { name: 'Elif Şahin', role: 'Pazarlama Müdürü', rating: 5, daysAgo: 90, text: 'Kurumsal sitemiz markamızın hak ettiği görüntüye kavuştu. Yatırımcı toplantılarında sitenin profesyonel görünümünden bahsediliyor.' },
  { name: 'Mustafa Yıldız', role: 'E-ticaret Yöneticisi', rating: 5, daysAgo: 18, text: 'Online mağazamızın yüklenme süresini yarıya düşürdüler. Sepete ekleme oranımız ölçülebilir biçimde arttı.' },
  { name: 'Esra Yıldırım', role: 'Klinik Sahibi', rating: 5, daysAgo: 7, text: 'Klinik için yaptıkları hasta takip sistemi son derece kullanışlı. Personelim hızlıca öğrendi, randevu çakışması yaşamıyoruz.' },
  { name: 'Ali Öztürk', role: 'Mimarlık Ofisi', rating: 4, daysAgo: 200, text: 'Portföy sitemizi tertemiz teslim ettiler. Tek talebimiz daha hızlı revizyon süreci olabilirdi; yine de sonuç çok iyi.' },
  { name: 'Hüseyin Aydın', role: 'Lojistik Firma', rating: 5, daysAgo: 45, text: 'Sevkiyat takip panelimiz tam istediğimiz gibi çalışıyor. Müşteri çağrılarımız azaldı çünkü bilgilere kendileri ulaşabiliyor.' },
  { name: 'Burcu Özdemir', role: 'İK Danışmanı', rating: 5, daysAgo: 32, text: 'Aday başvuru ve değerlendirme süreçlerimizi dijitale taşıdılar. Süreçler artık çok daha şeffaf.' },
  { name: 'Emre Arslan', role: 'Startup Kurucusu', rating: 5, daysAgo: 14, text: 'MVP\'mizi 6 haftada teslim ettiler. Hem teknik kalite hem süreç yönetimi beklentinin üzerinde.' },
  { name: 'Burak Doğan', role: 'Mağaza Sahibi', rating: 5, daysAgo: 22, text: 'Birden fazla şubemizi tek panelden yönetiyoruz. Stok ve satış takibi çok pratikleşti.' },
  { name: 'Cem Kılıç', role: 'Avukat', rating: 4, daysAgo: 100, text: 'Hukuk büromuz için kurdukları dosya takip sistemi son derece güvenli ve kullanışlı.' },
  { name: 'Selin Aslan', role: 'İçerik Üreticisi', rating: 5, daysAgo: 9, text: 'Kişisel sitemi 1 haftada teslim ettiler. Sayfa hızı ve SEO sonuçları beklediğimden çok iyi.' },
  { name: 'Pınar Çetin', role: 'Eğitim Kurumu', rating: 5, daysAgo: 75, text: 'Eğitim platformumuza canlı ders ve ödev modülü ekledirdik. Öğretmen ve öğrencilerden çok olumlu geri dönüş aldık.' },
  { name: 'Defne Kara', role: 'Diş Hekimi', rating: 5, daysAgo: 4, text: 'Hasta randevu ve hatırlatma sistemi mükemmel çalışıyor. SMS bildirimleri sayesinde no-show oranımız düştü.' },
  { name: 'Onur Koç', role: 'Üretim Tesisi Yöneticisi', rating: 5, daysAgo: 50, text: 'Fabrika içi süreç takip yazılımı için bizimle çalıştılar. Verimliliğimiz ölçülebilir oranda arttı.' },
  { name: 'Kerem Kurt', role: 'Sigorta Acentesi', rating: 5, daysAgo: 36, text: 'Müşteri portföy yönetim sistemimiz mükemmel oldu. Tekliflerimizi artık çok daha hızlı sunabiliyoruz.' },
  { name: 'Gizem Özkan', role: 'Cafe İşletmecisi', rating: 5, daysAgo: 15, text: 'Online menü ve sipariş sistemimiz harika oldu. Paket servis cirosu %40 arttı.' },
  { name: 'İrem Şimşek', role: 'Butik Sahibi', rating: 5, daysAgo: 70, text: 'Instagram\'dan e-ticarete geçiş sürecimde her aşamada yanımdaydılar. Şimdi siparişlerimi web sitemden alıyorum.' },
  { name: 'Eren Polat', role: 'Spor Salonu Sahibi', rating: 5, daysAgo: 25, text: 'Üyelik takip ve antrenman planlama sistemi çok başarılı. Üyelerimiz uygulamayı kullanıyor, memnunlar.' },
  { name: 'Ozan Çakır', role: 'Reklam Ajansı', rating: 4, daysAgo: 130, text: 'Müşterimiz adına yaptıkları işin kalitesi tartışılmaz. Birkaç küçük revizyon dışında her şey kusursuzdu.' },
  { name: 'Murat Erdoğan', role: 'İnşaat Firması', rating: 5, daysAgo: 80, text: 'Kurumsal sitemiz, projelerimizi vitrinlemek için tam ihtiyacımız olan şeydi. Yatırımcı görüşmelerimiz daha kaliteli geçiyor.' },
  { name: 'Tolga Güneş', role: 'Otomotiv Servisi', rating: 5, daysAgo: 11, text: 'Servis randevu ve müşteri takip sistemini kurdurduk. Personelim de müşterilerim de çok memnun.' },
  { name: 'Berk Aktaş', role: 'Optik Mağazası', rating: 5, daysAgo: 56, text: 'Stok ve satış takibimiz artık çok kolay. Birden fazla şube arasında transferi tek tıkla yapıyoruz.' },
  { name: 'Volkan Acar', role: 'Düğün Salonu', rating: 5, daysAgo: 40, text: 'Online rezervasyon ve müsaitlik takvimimiz harika çalışıyor. Çiftlerden olumlu yorumlar aldık.' },
  { name: 'Caner Korkmaz', role: 'Otel Yöneticisi', rating: 5, daysAgo: 95, text: 'Otel rezervasyon sistemimiz pürüzsüz çalışıyor. Komisyon ödemekten kurtulduk.' },
  { name: 'Hakan Ergin', role: 'Mağaza Müdürü', rating: 4, daysAgo: 220, text: 'POS entegrasyonunda küçük gecikme oldu ama sonunda kusursuz çalıştı. Kararlı yazılım.' },
  { name: 'Serkan Akın', role: 'Yazılım Geliştirici', rating: 5, daysAgo: 13, text: 'Bir meslektaş olarak söylüyorum: temiz kod, mantıklı mimari, doğru teknik seçimler. Üretkenlik kazandık.' },
  { name: 'Yusuf Çiftçi', role: 'Çiftlik İşletmesi', rating: 5, daysAgo: 88, text: 'Üretim ve sevkiyat takibi için hazırladıkları sistem işimizi kolaylaştırdı. Geliştiriciler tarımı anlayan bir bakış sergilediler.' },
  { name: 'Erkan Bozkurt', role: 'Mobilya Üreticisi', rating: 5, daysAgo: 47, text: 'Ürün katalog sitemiz beklediğimden çok daha şık çıktı. B2B müşterilerimizden çok pozitif dönüş aldık.' },
  { name: 'Kaan Bulut', role: 'Tekstil Firması', rating: 5, daysAgo: 19, text: 'İhracat müşterilerimize çok dilli site sundular. Yurt dışı taleplerimiz arttı.' },
  { name: 'Bora Köse', role: 'Kuaför', rating: 5, daysAgo: 8, text: 'Salonum için yaptıkları randevu sistemi sadece online değil, hatırlatma SMS\'i de gönderiyor. İptal oranımız düştü.' },
  { name: 'Sinan Soylu', role: 'Pastane Sahibi', rating: 5, daysAgo: 33, text: 'Pasta siparişlerimizi online aldığımız sistem çok pratik. Müşteriler özelleştirmelerini girebiliyor.' },
  { name: 'Doruk Ekinci', role: 'Spor Mağazası', rating: 5, daysAgo: 52, text: 'E-ticaret sitemizin checkout süreci çok hızlı. Sepet terkimiz azaldı.' },
  { name: 'Tunç Türk', role: 'Çiçekçi', rating: 5, daysAgo: 16, text: 'Çevrimiçi sipariş ve teslimat takip sistemimiz çiçek gibi çalışıyor. Müşteri memnuniyeti yüksek.' },
  { name: 'Engin Erdem', role: 'Veteriner', rating: 5, daysAgo: 41, text: 'Hasta kayıtları ve randevu sistemini dijitale taşıdılar. Klinikteki düzenimiz çok değişti.' },
  { name: 'Aykut Akkaya', role: 'Eczane Sahibi', rating: 5, daysAgo: 65, text: 'Stok takip ve sipariş sistemini kurmamızda çok yardımcı oldular. Eksik ilaç problemimiz neredeyse bitti.' },
  { name: 'Cenk Demirci', role: 'Konsept Mağaza', rating: 4, daysAgo: 180, text: 'Tasarım odaklı bir e-ticaret sitesi istemiştik, beklentimizi karşıladı. Daha hızlı geri dönüş olabilirdi.' },
  { name: 'Levent Yetkin', role: 'Müzik Stüdyosu', rating: 5, daysAgo: 24, text: 'Stüdyo rezervasyon sistemimiz harika oldu. Sanatçılarımız uygulamayı çok beğendi.' },
  { name: 'Mert Avcı', role: 'Yatırımcı İlişkileri', rating: 5, daysAgo: 110, text: 'Yatırımcı sayfamızı modernize ettiler. Finansal raporlara erişim daha kolay artık.' },
  { name: 'Can Akman', role: 'Sigorta Brokeri', rating: 5, daysAgo: 29, text: 'Müşterilerimiz online teklif alabiliyor. Çağrı merkezi yükümüz azaldı.' },
  { name: 'Deniz Tekin', role: 'Diyetisyen', rating: 5, daysAgo: 6, text: 'Danışan takip uygulaması harika oldu. Beslenme programlarını uygulama üzerinden takip ediyoruz.' },
  { name: 'Furkan Tan', role: 'Fotoğrafçı', rating: 5, daysAgo: 17, text: 'Portfolyo sitem tam istediğim gibi minimalist ve hızlı. Müşterilerim galeriyi çok beğeniyor.' },
  { name: 'İlker Vural', role: 'Müşavir', rating: 5, daysAgo: 78, text: 'Müşteri evraklarını dijital ortamda takip ettiğimiz panel ofisteki kâğıt yığınını bitirdi.' },
  { name: 'Ercan Karaca', role: 'Galeri Müdürü', rating: 5, daysAgo: 39, text: 'İkinci el araç sitemiz Google\'da üst sıralarda çıkmaya başladı. Etkili SEO çalışması yaptılar.' },
  { name: 'Tayfun Sevinç', role: 'İlaçlama Şirketi', rating: 5, daysAgo: 21, text: 'Servis takip ve randevu sistemini kurdular. Müşteri memnuniyetimiz ölçülebilir biçimde arttı.' },
  { name: 'Önder Alkan', role: 'Hastane Yöneticisi', rating: 5, daysAgo: 105, text: 'Hasta portali kurulumunda titiz bir çalışma yaptılar. KVKK uyumu eksiksiz.' },
  { name: 'Sezgin Karadağ', role: 'İhracat Müdürü', rating: 5, daysAgo: 60, text: 'Çok dilli kurumsal sitemiz sayesinde yurt dışı sorgu trafiği iki katına çıktı.' },
  { name: 'Emir Korkut', role: 'E-spor Organizatörü', rating: 5, daysAgo: 12, text: 'Turnuva yönetim platformumuz çok stabil çalışıyor. Yüksek trafikte bile sorun yaşamadık.' },
  { name: 'Yiğit Sönmez', role: 'Lokanta Sahibi', rating: 5, daysAgo: 55, text: 'Online sipariş ve günlük rapor sistemi sayesinde işletmemi anlık takip edebiliyorum.' },
  { name: 'Halil Yiğit', role: 'Tatil Köyü Yöneticisi', rating: 5, daysAgo: 38, text: 'Online rezervasyon platformumuz çok hızlı ve sağlam. Müşteri yorumları olumlu.' },
  { name: 'Ufuk Erol', role: 'Galeri Müdürü', rating: 5, daysAgo: 48, text: 'Sanat galerimiz için çok zarif bir site tasarladılar. Online sergi ziyaretçi sayısı artıyor.' },
  { name: 'Çağlar Boz', role: 'Düğün Fotoğrafçısı', rating: 5, daysAgo: 26, text: 'Müşterilerime özel galeri linki gönderdiğim sistemim mükemmel çalışıyor.' },
  { name: 'Berkay Gül', role: 'Boya Bayii', rating: 4, daysAgo: 160, text: 'Bayilik portalımız sayesinde sipariş süreçlerimiz dijitalleşti. Memnunuz.' },
  { name: 'Okan Kaplan', role: 'Spa Yöneticisi', rating: 5, daysAgo: 19, text: 'Online randevu ve paket satış sistemimiz harika oldu. Müşteri sayısı arttı.' },
  { name: 'Tarık Toprak', role: 'Tarım Şirketi', rating: 5, daysAgo: 72, text: 'Üretici takip sistemi kurmamızda çok yardımcı oldular. Sahaya gitmeden raporlama yapabiliyoruz.' },
  { name: 'Anıl Pala', role: 'Müzik Akademisi', rating: 5, daysAgo: 44, text: 'Öğrenci ve ders takip platformumuz mükemmel. Velilerden olumlu yorumlar aldık.' },
  { name: 'Erdem Eren', role: 'Gözlükçü', rating: 5, daysAgo: 31, text: 'Stok ve müşteri kayıt sistemi sayesinde işlerimiz çok hızlandı.' },
  { name: 'Bülent Yener', role: 'Site Yöneticisi', rating: 4, daysAgo: 140, text: 'Apartman yönetim platformumuz iyi çalışıyor. İletişim daha düzenli.' },
  { name: 'Akın Erdoğan', role: 'Online Eğitmen', rating: 5, daysAgo: 23, text: 'Eğitim platformumun video oynatıcısı çok hızlı ve sorunsuz. Öğrenciler memnun.' },
  { name: 'Selçuk Yıldırım', role: 'Atölye Sahibi', rating: 5, daysAgo: 67, text: 'Sipariş takip ve müşteri yönetim sistemini kurdurttuk. Çok pratik.' },
  { name: 'Atilla Gül', role: 'Kuyumcu', rating: 5, daysAgo: 53, text: 'Stok takibi ve günlük altın fiyatları senkronizasyonu mükemmel oldu.' },
  { name: 'Sercan Kaplan', role: 'Bowling Salonu', rating: 5, daysAgo: 18, text: 'Online rezervasyon ve grup organizasyon sistemi harika çalışıyor.' },
  { name: 'Soner Demirci', role: 'Yat Kiralama', rating: 5, daysAgo: 91, text: 'Çoklu dil destekli rezervasyon sistemimiz yurt dışı müşteri trafiğini artırdı.' },
  { name: 'Ata Akın', role: 'Anaokulu Müdürü', rating: 5, daysAgo: 34, text: 'Veli iletişim ve duyuru paneli mükemmel. İletişim çok daha hızlı oldu.' },
  { name: 'Fatma Şahin', role: 'Butik İşletmecisi', rating: 5, daysAgo: 10, text: 'Instagram entegrasyonlu e-ticaret sitemiz harika oldu. Sipariş hacmi 3 katına çıktı.' },
  { name: 'Merve Polat', role: 'Sosyal Medya Uzmanı', rating: 5, daysAgo: 25, text: 'Müşterimin sitesi hem hızlı hem estetik oldu. Tasarım anlayışları üst düzey.' },
  { name: 'Ece Kurt', role: 'Pet Shop Sahibi', rating: 5, daysAgo: 49, text: 'Online sipariş ve abonelik sistemimiz pet sahiplerine çok kolaylık sağladı.' },
  { name: 'Yasemin Çelik', role: 'Bakery Sahibi', rating: 5, daysAgo: 62, text: 'Pasta sipariş sistemimiz görsel olarak da çok başarılı. Müşteriler kataloğa bayılıyor.' },
  { name: 'Nazlı Doğan', role: 'Catering Şirketi', rating: 5, daysAgo: 27, text: 'Etkinlik ve menü yönetimi platformumuz iş yükümü ciddi azalttı.' },
  { name: 'Ceren Aydın', role: 'Halı Saha İşletmecisi', rating: 5, daysAgo: 14, text: 'Saat bazlı online rezervasyon sistemimiz mükemmel. Boş saat kalmıyor.' },
  { name: 'Ebru Yılmaz', role: 'Yoga Eğitmeni', rating: 5, daysAgo: 37, text: 'Online ders ve ödeme entegrasyonu çok pratik. Öğrencilerim memnun.' },
  { name: 'Asya Kaya', role: 'Estetisyen', rating: 5, daysAgo: 8, text: 'Salon yönetim panelim hem randevu hem stok takibini birlikte yapıyor.' },
  { name: 'Çiğdem Demir', role: 'Lazer Epilasyon Merkezi', rating: 5, daysAgo: 71, text: 'Müşteri seans takip sistemi çok başarılı. Personelimin işini kolaylaştırdı.' },
  { name: 'Müge Köse', role: 'Beauty Salon Sahibi', rating: 5, daysAgo: 20, text: 'Müşteri kart takibi ve seans hatırlatma sistemi mükemmel oldu.' },
  { name: 'Hande Aslan', role: 'Aile Hekimi', rating: 5, daysAgo: 43, text: 'Hasta takip ve randevu sistemi gerçekten profesyonel düzeyde geliştirilmiş.' },
  { name: 'Eda Tekin', role: 'Klinik Yöneticisi', rating: 5, daysAgo: 58, text: 'Hasta verilerini güvenli ve KVKK uyumlu şekilde tutan bir sistemimiz var artık.' },
  { name: 'Cansu Vural', role: 'Pilates Stüdyosu', rating: 5, daysAgo: 30, text: 'Üyelik ve ders rezervasyon paneli mükemmel çalışıyor. Üyelerden olumlu yorumlar aldım.' },
  { name: 'Damla Karaca', role: 'Anaokulu Sahibi', rating: 5, daysAgo: 15, text: 'Veli iletişim panelimiz sayesinde günlük etkinlikleri velilere kolayca iletiyoruz.' },
  { name: 'Naz Sevinç', role: 'Dans Stüdyosu', rating: 5, daysAgo: 84, text: 'Online ders rezervasyon ve ödeme sistemi mükemmel oldu.' },
  { name: 'Beste Erdem', role: 'Çocuk Etkinlik Merkezi', rating: 5, daysAgo: 22, text: 'Doğum günü organizasyon rezervasyonlarını online aldığımız sistem çok pratik.' },
  { name: 'Aslı Toprak', role: 'Kişisel Bakım Salonu', rating: 5, daysAgo: 11, text: 'Müşteri kartları, randevular, ödemeler — hepsi tek panelden yönetiliyor.' },
  { name: 'Buse Akkaya', role: 'Spa Manager', rating: 5, daysAgo: 67, text: 'Paket hizmet satışları ve hediye çeki sistemleri çok başarılı.' },
  { name: 'Sena Yetkin', role: 'Cilt Bakım Uzmanı', rating: 5, daysAgo: 29, text: 'Müşterilerime özel bakım planları takip ettiğim sistem mükemmel.' },
  { name: 'Beril Avcı', role: 'Saç Şekillendirme Stüdyosu', rating: 5, daysAgo: 18, text: 'Salonumun online görünürlüğü arttı, randevu doluluğumuz %80\'lere çıktı.' },
  { name: 'Begüm Kaplan', role: 'Galeri Sanat Yönetmeni', rating: 5, daysAgo: 51, text: 'Sanatçılarımızın eserlerini sergilediğimiz online galeri çok şık oldu.' },
  { name: 'Lara Pala', role: 'Konsept Cafe Sahibi', rating: 5, daysAgo: 9, text: 'Cafe için yapılan site hem menü hem etkinlik takvimi tek yerde topluyor.' },
  { name: 'Melis Gül', role: 'Fitness Eğitmeni', rating: 5, daysAgo: 42, text: 'Online ders satış ve takip sistemim gelirimde ciddi artış sağladı.' },
  { name: 'Funda Kara', role: 'Modaevi Sahibi', rating: 5, daysAgo: 35, text: 'Özel dikim sipariş takip sistemimiz çok başarılı. Müşterilerimiz aşamaları görüyor.' },
  { name: 'Esin Demir', role: 'Şarküteri Sahibi', rating: 5, daysAgo: 64, text: 'Online sipariş ve abonelik sistemimiz haftalık paket satışlarımızı artırdı.' },
  { name: 'Selen Şahin', role: 'Çiçekçi', rating: 5, daysAgo: 13, text: 'Online sipariş ve teslimat takip sistemi sevgililer gününde test edildi, hiç aksaklık olmadı.' },
  { name: 'Şeyma Yıldırım', role: 'Kuaför', rating: 5, daysAgo: 27, text: 'Hatırlatma SMS\'leri sayesinde unutulan randevular azaldı.' },
  { name: 'Gül Aktaş', role: 'Yoga Stüdyosu', rating: 5, daysAgo: 86, text: 'Sınıf rezervasyonu ve üyelik paneli pürüzsüz çalışıyor.' },
  { name: 'Demet Korkmaz', role: 'Diş Kliniği', rating: 5, daysAgo: 19, text: 'Hasta randevu ve ödeme takip sistemimiz mükemmel.' },
  { name: 'Berna Bozkurt', role: 'Lokanta Sahibi', rating: 5, daysAgo: 5, text: 'QR kodlu menü ve sipariş sistemimiz pandemi sonrasında çok işe yaradı.' },
  { name: 'Nehir Erdoğan', role: 'Optik Mağaza', rating: 4, daysAgo: 175, text: 'Stok ve sipariş takip sistemimiz iyi çalışıyor, küçük revizyon talepleri hızlı karşılandı.' },
  { name: 'Şule Çakır', role: 'Nail Art Salonu', rating: 5, daysAgo: 24, text: 'Salon yönetim sistemi hem randevu hem ürün satış takibini birlikte yapıyor.' },
  { name: 'Tülay Polat', role: 'Çocuk Doktoru', rating: 5, daysAgo: 56, text: 'Hasta takip ve aşı hatırlatma sistemi çok başarılı oldu. Velilerden teşekkür alıyoruz.' },
  { name: 'Nuray Şimşek', role: 'Galeri Sahibi', rating: 5, daysAgo: 47, text: 'Otomotiv galerimiz için dijital vitrin oluşturdular. Test sürüş randevuları arttı.' },
  { name: 'Gülşen Tunç', role: 'Estetik Klinik', rating: 5, daysAgo: 38, text: 'Online danışma ve randevu sistemi sayesinde hasta sayımız arttı.' },
];
